In [1]:
import pandas as pd

In [3]:
renaud = pd.read_clipboard()

In [5]:
charl = pd.read_clipboard()

In [6]:
charl

         JOB
0   ICEM200Q
1   Icgm014q
2   ICGM103Q
3   ICGM172M
4   NCGM001M
..       ...
56  ISYM901Q
57  ISYM902Q
58  ISYM906Q
59  ISYM908Q
60  ITEM051Q

[61 rows x 1 columns]

In [7]:
renaud

         JOB
0   NBMY645A
1   NBMY645H
2   NBMY645M
3   NBMY645Q
4   NBMY648Q
5   NBMY650A
6   NBMY650H
7   NBMY650M
8   NBMY650Q
9   NBMY653Q
10  IEGF007Q
11  IEGG007Q
12  IEGM007Q
13  NBMY246Q
14  NBMY251Q
15  NBMY605A
16  NBMY605H
17  NBMY605M
18  NBMY605Q
19  NBMY608Q
20  NBMY611Q
21  NBMY615A
22  NBMY615H
23  NBMY615M
24  NBMY615Q
25  NBMY618Q
26  NBMY620A
27  NBMY620H
28  NBMY620M
29  NBMY620Q
30  NBMY623Q
31  NBMY626Q
32  NBMY628Q
33  NBMY630A
34  NBMY630H
35  NBMY630M
36  NBMY630Q
37  NBMY633Q
38  NBMY635A
39  NBMY635H
40  NBMY635M
41  NBMY635Q
42  NBMY638Q
43  NBMY640A
44  NBMY640H
45  NBMY640M
46  NBMY640Q
47  NBMY643Q
48  NBMY658Q
49  NBMY665A
50  NBMY665H
51  NBMY665M
52  NBMY665Q
53  NBMY668Q
54  NBMY677Q
55  NBMY680Q
56  NCGM001M
57  NISY500Q
58  NISY600H
59  NISY700M

In [9]:
renaud.shape

(60, 1)

In [10]:
renaud.columns

Index(['JOB'], dtype='object')

In [19]:
dif = []
for i in renaud.JOB:
    if i not in charl.JOB:
        print(len(i))
        dif.append(i)

8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8

In [14]:
len(dif)

60

In [18]:
for i in charl.JOB:
    if i not in renaud.JOB:
        print(len(i))

8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8

In [24]:
r = renaud.JOB.values.tolist()
c = charl.JOB.values.tolist()

In [26]:
for i in c:
    if i not in r:
        print(i)

ICEM200Q
Icgm014q
ICGM103Q
ICGM172M
iegm082q
BSYM900Q
BSYM901Q
BSYM902Q
ISYM900Q
ISYM901Q
ISYM902Q
ISYM906Q
ISYM908Q
ITEM051Q